/* =========================================================
   GÖMÜLÜ KELİME SÖZLÜĞÜ — en sık kullanılan İngilizce kelimeler
   İnternet/çeviri servisi olmadan da kelime anlamları anında gösterilir.
   Birden çok anlam virgülle ayrılır: ilki ana karşılık, kalanlar
   "diğer anlamlar" olarak listelenir.
   ========================================================= */
window.WORD_TR = {
    // ——— İşlev kelimeleri ———
    "the": "(belirli tanımlık: o, bu)",
    "a": "bir (herhangi)",
    "an": "bir (herhangi)",
    "and": "ve",
    "or": "veya, ya da",
    "but": "ama, fakat",
    "if": "eğer, -se",
    "so": "bu yüzden, böylece, çok",
    "because": "çünkü",
    "although": "her ne kadar, -e rağmen",
    "though": "gerçi, yine de",
    "while": "iken, sırasında; oysa",
    "when": "ne zaman, -dığında",
    "where": "nerede, -dığı yer",
    "why": "neden, niçin",
    "how": "nasıl",
    "what": "ne",
    "which": "hangi, ki o",
    "who": "kim",
    "whom": "kimi, kime",
    "whose": "kimin",
    "that": "şu; ki",
    "this": "bu",
    "these": "bunlar",
    "those": "şunlar, onlar",
    "whatever": "her ne, ne olursa olsun",
    "whoever": "her kim",
    "whenever": "her ne zaman",
    "wherever": "her nerede",
    "however": "ancak, bununla birlikte; her nasıl",
    "therefore": "bu nedenle, dolayısıyla",
    "moreover": "dahası, üstelik",
    "furthermore": "ayrıca, bundan başka",
    "nevertheless": "yine de, buna rağmen",
    "meanwhile": "bu arada, bu sırada",
    "otherwise": "aksi takdirde, yoksa",
    "unless": "-medikçe, olmazsa",
    "until": "-e kadar",
    "since": "-den beri; çünkü",
    "during": "boyunca, sırasında",
    "before": "önce, -den önce",
    "after": "sonra, -den sonra",
    "between": "arasında",
    "among": "arasında (çoklu)",
    "through": "içinden, boyunca; aracılığıyla",
    "throughout": "baştan başa, boyunca",
    "against": "karşı, aleyhine",
    "toward": "-e doğru",
    "towards": "-e doğru",
    "within": "içinde, dahilinde",
    "without": "olmadan, -sız",
    "despite": "-e rağmen",
    "beyond": "ötesinde, öteye",
    "above": "üstünde, yukarıda",
    "below": "altında, aşağıda",
    "under": "altında",
    "over": "üzerinde, üstünden; bitmiş",
    "about": "hakkında; yaklaşık",
    "around": "etrafında; yaklaşık",
    "across": "karşıya, boyunca",
    "along": "boyunca",
    "behind": "arkasında, geride",
    "beside": "yanında",
    "besides": "ayrıca, bunun yanında",
    "near": "yakın, yakınında",
    "inside": "içinde, içeride",
    "outside": "dışında, dışarıda",
    "into": "içine, -e",
    "onto": "üzerine",
    "upon": "üzerine, üzerinde",
    "of": "-in, -nin (aitlik)",
    "to": "-e, -a; için",
    "in": "içinde, -de",
    "on": "üzerinde, -de; açık",
    "at": "-de, -da (nokta)",
    "by": "tarafından; yanında; ile",
    "for": "için; süresince",
    "from": "-den, -dan",
    "with": "ile, birlikte",
    "as": "olarak; gibi; iken",
    "not": "değil, olumsuzluk eki",
    "no": "hayır; hiç",
    "yes": "evet",
    "all": "hepsi, tüm, bütün",
    "any": "herhangi, hiç",
    "some": "bazı, biraz",
    "many": "birçok, çok sayıda",
    "much": "çok (miktar)",
    "few": "az, birkaç",
    "little": "küçük; az",
    "more": "daha çok, daha fazla",
    "most": "en çok, çoğu",
    "less": "daha az",
    "least": "en az",
    "other": "diğer, başka",
    "another": "başka bir, bir tane daha",
    "such": "böyle, bu tür",
    "same": "aynı",
    "different": "farklı, değişik",
    "each": "her (biri)",
    "every": "her",
    "either": "ikisinden biri; ya ... ya",
    "neither": "ikisi de değil, ne ... ne",
    "both": "her ikisi, ikisi de",
    "several": "birkaç, çeşitli",
    "enough": "yeterli, yeterince",
    "only": "sadece, yalnızca; tek",
    "just": "sadece; henüz; tam",
    "even": "hatta, bile; düz",
    "also": "ayrıca, de/da",
    "too": "de/da; fazla, aşırı",
    "very": "çok",
    "quite": "oldukça, epey",
    "rather": "oldukça; daha ziyade",
    "almost": "neredeyse, hemen hemen",
    "nearly": "neredeyse",
    "always": "her zaman, daima",
    "usually": "genellikle",
    "often": "sık sık, çoğu kez",
    "sometimes": "bazen",
    "rarely": "nadiren",
    "seldom": "nadiren, seyrek",
    "never": "asla, hiçbir zaman",
    "again": "tekrar, yeniden",
    "still": "hâlâ; yine de; durgun",
    "yet": "henüz; yine de",
    "soon": "yakında, birazdan",
    "now": "şimdi, şu anda",
    "then": "o zaman; sonra",
    "here": "burada, buraya",
    "there": "orada, oraya",
    "today": "bugün",
    "tomorrow": "yarın",
    "yesterday": "dün",
    "already": "zaten, çoktan",
    "perhaps": "belki",
    "maybe": "belki",
    "probably": "muhtemelen, büyük olasılıkla",
    "certainly": "kesinlikle, elbette",
    "definitely": "kesinlikle",
    "actually": "aslında, gerçekte",
    "really": "gerçekten",
    "especially": "özellikle",
    "particularly": "özellikle, bilhassa",
    "generally": "genellikle, genel olarak",
    "basically": "temelde, esasen",
    "exactly": "tam olarak, aynen",
    "instead": "yerine, onun yerine",
    "together": "birlikte, beraber",
    "away": "uzakta, uzağa",
    "back": "geri; arka; sırt",
    "down": "aşağı, aşağıya",
    "up": "yukarı, yukarıya",
    "out": "dışarı, dışarıda",
    "off": "kapalı; uzakta; -den",
    "again": "tekrar, yeniden",
    // ——— Zamirler ———
    "i": "ben",
    "you": "sen, siz",
    "he": "o (erkek)",
    "she": "o (kadın)",
    "it": "o (cansız/hayvan)",
    "we": "biz",
    "they": "onlar",
    "me": "beni, bana",
    "him": "onu, ona (erkek)",
    "her": "onu, ona (kadın); onun",
    "us": "bizi, bize",
    "them": "onları, onlara",
    "my": "benim",
    "your": "senin, sizin",
    "his": "onun (erkek)",
    "its": "onun (cansız)",
    "our": "bizim",
    "their": "onların",
    "mine": "benimki",
    "yours": "seninki, sizinki",
    "ours": "bizimki",
    "theirs": "onlarınki",
    "myself": "kendim",
    "yourself": "kendin",
    "himself": "kendisi (erkek)",
    "herself": "kendisi (kadın)",
    "itself": "kendisi (cansız)",
    "ourselves": "kendimiz",
    "themselves": "kendileri",
    "someone": "birisi, biri",
    "somebody": "birisi",
    "something": "bir şey",
    "somewhere": "bir yerde",
    "anyone": "herhangi biri, hiç kimse",
    "anybody": "herhangi biri",
    "anything": "herhangi bir şey, hiçbir şey",
    "anywhere": "herhangi bir yerde",
    "everyone": "herkes",
    "everybody": "herkes",
    "everything": "her şey",
    "everywhere": "her yerde",
    "nobody": "hiç kimse",
    "nothing": "hiçbir şey",
    "nowhere": "hiçbir yerde",
    "none": "hiçbiri",
    // ——— Temel fiiller ———
    "be": "olmak",
    "am": "-im (olmak)",
    "is": "-dir (olmak)",
    "are": "-dir(ler) (olmak)",
    "was": "idi (olmak)",
    "were": "idiler (olmak)",
    "been": "olmuş",
    "being": "olma, varlık",
    "have": "sahip olmak; -miş olmak",
    "has": "sahip (o); -miş",
    "had": "sahipti; -mişti",
    "do": "yapmak, etmek",
    "does": "yapar (o)",
    "did": "yaptı",
    "done": "yapılmış, bitmiş",
    "doing": "yapma, yaparak",
    "will": "-ecek, -acak; irade",
    "would": "-erdi, -ardı",
    "can": "-ebilmek; konserve",
    "could": "-ebilirdi",
    "may": "-ebilir (izin/olasılık)",
    "might": "-ebilir (zayıf olasılık)",
    "must": "-meli, zorunda olmak",
    "shall": "-ecek (resmî)",
    "should": "-meli (öneri)",
    "ought": "-meli, gerekmek",
    "need": "ihtiyaç duymak, gerekmek; ihtiyaç",
    "dare": "cesaret etmek, cüret etmek",
    "go": "gitmek",
    "went": "gitti",
    "gone": "gitmiş",
    "going": "gitme; olacak",
    "come": "gelmek",
    "came": "geldi",
    "coming": "gelen, gelme",
    "get": "almak, elde etmek; olmak",
    "got": "aldı, oldu",
    "gotten": "alınmış, olunmuş",
    "make": "yapmak, üretmek",
    "made": "yaptı, yapılmış",
    "making": "yapma, yapım",
    "take": "almak, götürmek",
    "took": "aldı",
    "taken": "alınmış",
    "taking": "alma",
    "give": "vermek",
    "gave": "verdi",
    "given": "verilmiş; belirli",
    "put": "koymak, yerleştirmek",
    "keep": "tutmak, saklamak; devam etmek",
    "kept": "tuttu, sakladı",
    "let": "izin vermek, bırakmak",
    "say": "söylemek, demek",
    "said": "söyledi, dedi",
    "saying": "söz, deyiş; söyleme",
    "tell": "anlatmak, söylemek",
    "told": "anlattı, söyledi",
    "speak": "konuşmak",
    "spoke": "konuştu",
    "spoken": "konuşulmuş; sözlü",
    "talk": "konuşmak, sohbet etmek",
    "ask": "sormak; istemek",
    "answer": "cevaplamak; cevap",
    "call": "aramak, çağırmak; çağrı",
    "know": "bilmek, tanımak",
    "knew": "bildi, tanıdı",
    "known": "bilinen, tanınmış",
    "think": "düşünmek, sanmak",
    "thought": "düşündü; düşünce",
    "believe": "inanmak",
    "understand": "anlamak",
    "understood": "anladı, anlaşılmış",
    "remember": "hatırlamak",
    "forget": "unutmak",
    "forgot": "unuttu",
    "learn": "öğrenmek",
    "learned": "öğrendi; bilgili",
    "teach": "öğretmek",
    "taught": "öğretti",
    "study": "çalışmak, incelemek; çalışma",
    "read": "okumak",
    "write": "yazmak",
    "wrote": "yazdı",
    "written": "yazılı, yazılmış",
    "see": "görmek",
    "saw": "gördü; testere",
    "seen": "görülmüş",
    "look": "bakmak; görünmek; bakış",
    "watch": "izlemek; saat",
    "hear": "duymak, işitmek",
    "heard": "duydu",
    "listen": "dinlemek",
    "feel": "hissetmek",
    "felt": "hissetti; keçe",
    "touch": "dokunmak; temas",
    "smell": "koklamak; koku",
    "taste": "tatmak; tat, zevk",
    "seem": "görünmek, gibi gelmek",
    "appear": "görünmek, ortaya çıkmak",
    "look": "bakmak; görünmek",
    "want": "istemek",
    "wish": "dilemek; dilek",
    "hope": "umut etmek; umut",
    "like": "sevmek, hoşlanmak; gibi",
    "love": "sevmek; aşk, sevgi",
    "hate": "nefret etmek",
    "prefer": "tercih etmek",
    "enjoy": "keyif almak, zevk almak",
    "live": "yaşamak; canlı",
    "die": "ölmek",
    "died": "öldü",
    "dead": "ölü",
    "death": "ölüm",
    "born": "doğmuş",
    "eat": "yemek",
    "ate": "yedi",
    "eaten": "yenmiş",
    "drink": "içmek; içecek",
    "drank": "içti",
    "sleep": "uyumak; uyku",
    "slept": "uyudu",
    "wake": "uyanmak, uyandırmak",
    "woke": "uyandı",
    "walk": "yürümek; yürüyüş",
    "run": "koşmak; çalıştırmak, yönetmek",
    "ran": "koştu",
    "running": "koşma; çalışan",
    "jump": "zıplamak, atlamak",
    "sit": "oturmak",
    "sat": "oturdu",
    "stand": "ayakta durmak; dayanmak",
    "stood": "durdu",
    "stay": "kalmak",
    "leave": "ayrılmak; bırakmak; izin",
    "left": "ayrıldı; sol; kalan",
    "arrive": "varmak, ulaşmak",
    "return": "dönmek; iade etmek; dönüş",
    "move": "hareket etmek; taşınmak; hamle",
    "moved": "taşındı, hareket etti; duygulanmış",
    "stop": "durmak, durdurmak; durak",
    "start": "başlamak, başlatmak; başlangıç",
    "started": "başladı",
    "begin": "başlamak",
    "began": "başladı",
    "begun": "başlanmış",
    "finish": "bitirmek; bitiş",
    "end": "bitmek; son, uç",
    "continue": "devam etmek",
    "open": "açmak; açık",
    "close": "kapatmak; yakın",
    "closed": "kapalı",
    "turn": "dönmek, çevirmek; sıra",
    "bring": "getirmek",
    "brought": "getirdi",
    "carry": "taşımak",
    "send": "göndermek",
    "sent": "gönderdi",
    "receive": "almak (teslim)",
    "buy": "satın almak",
    "bought": "satın aldı",
    "sell": "satmak",
    "sold": "sattı, satılmış",
    "pay": "ödemek",
    "paid": "ödedi, ödenmiş",
    "cost": "mal olmak; maliyet",
    "spend": "harcamak, geçirmek",
    "spent": "harcadı, geçirdi",
    "save": "kurtarmak; biriktirmek; kaydetmek",
    "lose": "kaybetmek",
    "lost": "kaybetti; kayıp",
    "find": "bulmak",
    "found": "buldu; kurmak",
    "win": "kazanmak",
    "won": "kazandı",
    "beat": "yenmek; vurmak, atmak (kalp)",
    "play": "oynamak, çalmak; oyun",
    "work": "çalışmak; iş; işe yaramak",
    "worked": "çalıştı",
    "working": "çalışan, çalışma",
    "help": "yardım etmek; yardım",
    "try": "denemek, çalışmak",
    "tried": "denedi",
    "use": "kullanmak; kullanım",
    "used": "kullanılmış; alışkın",
    "using": "kullanarak",
    "show": "göstermek; gösteri",
    "showed": "gösterdi",
    "shown": "gösterilmiş",
    "wear": "giymek",
    "wore": "giydi",
    "worn": "giyilmiş, eskimiş",
    "meet": "buluşmak, tanışmak; karşılamak",
    "met": "buluştu, tanıştı",
    "meeting": "toplantı; buluşma",
    "visit": "ziyaret etmek; ziyaret",
    "wait": "beklemek",
    "hold": "tutmak; düzenlemek",
    "held": "tuttu, düzenlendi",
    "catch": "yakalamak",
    "caught": "yakaladı",
    "throw": "atmak, fırlatmak",
    "threw": "attı",
    "thrown": "atılmış",
    "pull": "çekmek",
    "push": "itmek; baskı yapmak",
    "press": "basmak; baskı; basın",
    "pressed": "bastı, basılmış",
    "cut": "kesmek; kesik",
    "break": "kırmak; ara, mola",
    "broke": "kırdı; beş parasız",
    "broken": "kırık, bozuk",
    "build": "inşa etmek, kurmak",
    "built": "inşa etti, kurulmuş",
    "create": "yaratmak, oluşturmak",
    "created": "oluşturdu",
    "destroy": "yok etmek, tahrip etmek",
    "kill": "öldürmek",
    "grow": "büyümek, yetiştirmek",
    "grew": "büyüdü",
    "grown": "büyümüş, yetişkin",
    "change": "değiştirmek, değişmek; değişim; bozuk para",
    "changed": "değişti",
    "become": "olmak, haline gelmek",
    "became": "oldu",
    "happen": "olmak, meydana gelmek",
    "happened": "oldu, meydana geldi",
    "happening": "olan, olay",
    "occur": "meydana gelmek, oluşmak",
    "exist": "var olmak",
    "remain": "kalmak, geriye kalmak",
    "belong": "ait olmak",
    "include": "içermek, dahil etmek",
    "including": "dahil, içererek",
    "contain": "içermek, barındırmak",
    "consist": "oluşmak, ibaret olmak",
    "provide": "sağlamak, temin etmek",
    "offer": "sunmak, teklif etmek; teklif",
    "produce": "üretmek",
    "develop": "geliştirmek, gelişmek",
    "improve": "iyileştirmek, geliştirmek",
    "increase": "artmak, artırmak; artış",
    "decrease": "azalmak, azaltmak; azalış",
    "reduce": "azaltmak, düşürmek",
    "raise": "yükseltmek; (çocuk) büyütmek; zam",
    "rise": "yükselmek, doğmak; artış",
    "rose": "yükseldi; gül",
    "risen": "yükselmiş",
    "fall": "düşmek; sonbahar",
    "fell": "düştü",
    "fallen": "düşmüş",
    "drop": "düşürmek, damlamak; damla",
    "add": "eklemek",
    "remove": "kaldırmak, çıkarmak",
    "choose": "seçmek",
    "chose": "seçti",
    "chosen": "seçilmiş",
    "decide": "karar vermek",
    "decided": "karar verdi; kararlı",
    "decision": "karar",
    "agree": "aynı fikirde olmak, kabul etmek",
    "disagree": "aynı fikirde olmamak",
    "accept": "kabul etmek",
    "refuse": "reddetmek",
    "deny": "inkar etmek, reddetmek",
    "allow": "izin vermek",
    "let": "izin vermek, bırakmak",
    "prevent": "önlemek, engellemek",
    "avoid": "kaçınmak, sakınmak",
    "protect": "korumak",
    "attack": "saldırmak; saldırı",
    "defend": "savunmak",
    "fight": "savaşmak, kavga etmek; kavga",
    "fought": "savaştı",
    "argue": "tartışmak; savunmak",
    "discuss": "tartışmak, görüşmek",
    "explain": "açıklamak",
    "describe": "tanımlamak, betimlemek",
    "mention": "bahsetmek, değinmek",
    "suggest": "önermek; ima etmek",
    "recommend": "tavsiye etmek",
    "advise": "öğüt vermek, tavsiye etmek",
    "warn": "uyarmak",
    "promise": "söz vermek; söz",
    "expect": "beklemek, ummak",
    "suppose": "varsaymak, sanmak",
    "assume": "varsaymak; üstlenmek",
    "guess": "tahmin etmek; tahmin",
    "predict": "öngörmek, tahmin etmek",
    "prediction": "tahmin, öngörü",
    "imagine": "hayal etmek",
    "wonder": "merak etmek; harika",
    "doubt": "şüphe etmek; şüphe",
    "realize": "fark etmek; gerçekleştirmek",
    "recognize": "tanımak, fark etmek",
    "notice": "fark etmek; bildiri",
    "consider": "düşünmek, göz önünde bulundurmak",
    "compare": "karşılaştırmak",
    "measure": "ölçmek; önlem",
    "count": "saymak; önemli olmak",
    "calculate": "hesaplamak",
    "solve": "çözmek",
    "check": "kontrol etmek; çek",
    "test": "test etmek; sınav, deney",
    "prove": "kanıtlamak",
    "proved": "kanıtladı",
    "support": "desteklemek; destek",
    "supply": "tedarik etmek; arz",
    "demand": "talep etmek; talep",
    "require": "gerektirmek, istemek",
    "request": "rica etmek; istek",
    "order": "sipariş etmek; emretmek; düzen, sıra",
    "control": "kontrol etmek; denetim",
    "manage": "yönetmek; başarmak",
    "managed": "yönetti, başardı",
    "lead": "yönetmek, öncülük etmek; kurşun",
    "led": "yönetti, öncülük etti",
    "follow": "takip etmek, izlemek",
    "guide": "rehberlik etmek; rehber",
    "direct": "yönlendirmek; doğrudan",
    "serve": "hizmet etmek; servis yapmak",
    "share": "paylaşmak; pay, hisse",
    "join": "katılmak; birleştirmek",
    "connect": "bağlamak, bağlanmak",
    "attach": "iliştirmek, eklemek",
    "separate": "ayırmak; ayrı",
    "divide": "bölmek",
    "combine": "birleştirmek",
    "mix": "karıştırmak; karışım",
    "fill": "doldurmak",
    "empty": "boşaltmak; boş",
    "cover": "kaplamak, örtmek; kapak",
    "hide": "saklamak, gizlemek",
    "hid": "sakladı",
    "hidden": "gizli, saklı",
    "discover": "keşfetmek",
    "explore": "keşfetmek, araştırmak",
    "search": "aramak; arama",
    "seek": "aramak, peşinde olmak",
    "sought": "aradı",
    "reach": "ulaşmak, erişmek",
    "achieve": "başarmak, elde etmek",
    "succeed": "başarılı olmak",
    "fail": "başarısız olmak",
    "failed": "başarısız oldu",
    "failure": "başarısızlık",
    "success": "başarı",
    "successful": "başarılı",
    "attempt": "girişim; teşebbüs etmek",
    "effort": "çaba, gayret",
    "practice": "pratik yapmak; uygulama, alıştırma",
    "prepare": "hazırlamak, hazırlanmak",
    "plan": "planlamak; plan",
    "design": "tasarlamak; tasarım",
    "organize": "düzenlemek, organize etmek",
    "arrange": "düzenlemek, ayarlamak",
    "collect": "toplamak, biriktirmek",
    "gather": "toplamak, toplanmak",
    "pick": "seçmek; toplamak",
    "select": "seçmek",
    "apply": "başvurmak; uygulamak",
    "employ": "işe almak; kullanmak",
    "hire": "işe almak, kiralamak",
    "fire": "kovmak; ateş; yangın",
    "retire": "emekli olmak",
    "earn": "kazanmak (para)",
    "own": "sahip olmak; kendi",
    "owner": "sahip, mal sahibi",
    "borrow": "ödünç almak",
    "lend": "ödünç vermek",
    "owe": "borçlu olmak",
    "invest": "yatırım yapmak",
    "trade": "ticaret yapmak; ticaret, takas",
    "exchange": "değiş tokuş etmek; borsa, kur",
    "deliver": "teslim etmek",
    "travel": "seyahat etmek; yolculuk",
    "drive": "araba sürmek; itici güç",
    "drove": "sürdü",
    "driven": "sürülmüş; hırslı",
    "ride": "binmek; sürüş",
    "rode": "bindi",
    "fly": "uçmak; sinek",
    "flew": "uçtu",
    "flown": "uçmuş",
    "swim": "yüzmek",
    "swam": "yüzdü",
    "climb": "tırmanmak",
    "enter": "girmek",
    "exit": "çıkmak; çıkış",
    "escape": "kaçmak; kaçış",
    "hurry": "acele etmek; acele",
    "rush": "acele etmek; koşuşturma",
    "slow": "yavaş",
    "fast": "hızlı; oruç",
    "quick": "hızlı, çabuk",
    "quickly": "hızlıca, çabucak",
    "slowly": "yavaşça",
    "suddenly": "aniden",
    "immediately": "hemen, derhal",
    "finally": "sonunda, nihayet",
    "eventually": "sonunda, en nihayetinde",
    "recently": "son zamanlarda, geçenlerde",
    "currently": "şu anda, halen",
    "previously": "önceden, daha önce",
    "originally": "aslında, başlangıçta",
    // ——— İsimler ———
    "time": "zaman, vakit; kez",
    "year": "yıl",
    "month": "ay",
    "week": "hafta",
    "day": "gün",
    "hour": "saat (süre)",
    "minute": "dakika",
    "second": "saniye; ikinci",
    "moment": "an",
    "morning": "sabah",
    "afternoon": "öğleden sonra",
    "evening": "akşam",
    "night": "gece",
    "weekend": "hafta sonu",
    "century": "yüzyıl",
    "decade": "on yıl",
    "period": "dönem, süre",
    "age": "yaş; çağ",
    "history": "tarih, geçmiş",
    "future": "gelecek",
    "past": "geçmiş",
    "present": "şimdiki zaman; hediye; mevcut; sunmak",
    "world": "dünya",
    "earth": "dünya, yeryüzü; toprak",
    "country": "ülke; kırsal",
    "nation": "ulus, millet",
    "state": "devlet; eyalet; durum; belirtmek",
    "city": "şehir, kent",
    "town": "kasaba, şehir",
    "village": "köy",
    "place": "yer; yerleştirmek",
    "area": "alan, bölge",
    "region": "bölge",
    "location": "konum, yer",
    "space": "uzay; boşluk, alan",
    "environment": "çevre, ortam",
    "nature": "doğa; tabiat",
    "land": "toprak, kara; inmek",
    "ground": "zemin, yer; gerekçe",
    "water": "su",
    "air": "hava",
    "sea": "deniz",
    "ocean": "okyanus",
    "river": "nehir, ırmak",
    "lake": "göl",
    "mountain": "dağ",
    "forest": "orman",
    "tree": "ağaç",
    "flower": "çiçek",
    "plant": "bitki; fabrika; dikmek",
    "animal": "hayvan",
    "bird": "kuş",
    "fish": "balık; balık tutmak",
    "dog": "köpek",
    "cat": "kedi",
    "horse": "at",
    "human": "insan; insani",
    "people": "insanlar, halk",
    "person": "kişi, insan",
    "man": "adam, erkek",
    "men": "adamlar, erkekler",
    "woman": "kadın",
    "women": "kadınlar",
    "child": "çocuk",
    "children": "çocuklar",
    "baby": "bebek",
    "boy": "erkek çocuk, oğlan",
    "girl": "kız",
    "family": "aile",
    "parent": "ebeveyn, anne-baba",
    "mother": "anne",
    "father": "baba",
    "brother": "erkek kardeş",
    "sister": "kız kardeş",
    "son": "oğul",
    "daughter": "kız evlat",
    "husband": "koca, eş",
    "wife": "karı, eş",
    "friend": "arkadaş, dost",
    "neighbor": "komşu",
    "guest": "misafir, konuk",
    "stranger": "yabancı",
    "life": "hayat, yaşam",
    "body": "vücut, beden; gövde",
    "head": "baş, kafa; yönetmek",
    "face": "yüz; yüzleşmek",
    "eye": "göz",
    "ear": "kulak",
    "nose": "burun",
    "mouth": "ağız",
    "hand": "el; vermek",
    "arm": "kol; silahlandırmak",
    "leg": "bacak",
    "foot": "ayak; fit (ölçü)",
    "feet": "ayaklar",
    "heart": "kalp, yürek",
    "mind": "zihin, akıl; aldırmak",
    "brain": "beyin",
    "blood": "kan",
    "skin": "cilt, deri",
    "hair": "saç",
    "voice": "ses (insan)",
    "health": "sağlık",
    "disease": "hastalık",
    "illness": "hastalık, rahatsızlık",
    "pain": "acı, ağrı",
    "medicine": "ilaç; tıp",
    "doctor": "doktor",
    "hospital": "hastane",
    "patient": "hasta; sabırlı",
    "treatment": "tedavi; muamele",
    "food": "yiyecek, gıda",
    "bread": "ekmek",
    "meat": "et",
    "fruit": "meyve",
    "vegetable": "sebze",
    "milk": "süt",
    "coffee": "kahve",
    "tea": "çay",
    "sugar": "şeker",
    "salt": "tuz",
    "dinner": "akşam yemeği",
    "lunch": "öğle yemeği",
    "breakfast": "kahvaltı",
    "meal": "öğün, yemek",
    "restaurant": "restoran, lokanta",
    "kitchen": "mutfak",
    "house": "ev",
    "home": "ev, yuva",
    "room": "oda; yer",
    "door": "kapı",
    "window": "pencere",
    "wall": "duvar",
    "floor": "zemin, kat",
    "roof": "çatı",
    "table": "masa; tablo",
    "chair": "sandalye",
    "bed": "yatak",
    "garden": "bahçe",
    "building": "bina; inşa",
    "office": "ofis, büro; makam",
    "school": "okul",
    "university": "üniversite",
    "college": "yüksekokul, kolej",
    "class": "sınıf; ders",
    "course": "kurs, ders; rota",
    "lesson": "ders",
    "student": "öğrenci",
    "teacher": "öğretmen",
    "education": "eğitim",
    "knowledge": "bilgi",
    "science": "bilim",
    "research": "araştırma; araştırmak",
    "experiment": "deney",
    "theory": "teori, kuram",
    "fact": "gerçek, olgu",
    "truth": "gerçek, hakikat",
    "lie": "yalan; yalan söylemek; uzanmak",
    "information": "bilgi",
    "data": "veri",
    "number": "sayı, numara",
    "amount": "miktar, tutar",
    "part": "parça, bölüm; rol",
    "piece": "parça",
    "whole": "bütün, tüm",
    "half": "yarım, yarı",
    "quarter": "çeyrek",
    "percent": "yüzde",
    "example": "örnek",
    "case": "durum, vaka; dava; kılıf",
    "type": "tür, tip; yazmak",
    "kind": "tür, çeşit; nazik",
    "sort": "tür; sıralamak",
    "way": "yol; yöntem, şekil",
    "method": "yöntem, metot",
    "system": "sistem, düzen",
    "process": "süreç; işlemek",
    "result": "sonuç",
    "effect": "etki, sonuç",
    "cause": "neden; yol açmak",
    "reason": "neden, sebep; akıl",
    "purpose": "amaç, maksat",
    "goal": "hedef, amaç; gol",
    "aim": "amaç; hedeflemek",
    "target": "hedef",
    "problem": "sorun, problem",
    "issue": "konu, mesele; sayı (dergi)",
    "matter": "mesele; madde; önemli olmak",
    "question": "soru; sorgulamak",
    "solution": "çözüm",
    "situation": "durum",
    "condition": "koşul, şart; durum",
    "state": "durum; devlet; belirtmek",
    "position": "konum, pozisyon; görüş",
    "level": "seviye, düzey",
    "degree": "derece; diploma",
    "point": "nokta; puan; işaret etmek",
    "line": "çizgi, hat; sıra",
    "side": "taraf, yan",
    "edge": "kenar; avantaj",
    "center": "merkez, orta",
    "middle": "orta",
    "top": "üst, tepe; en iyi",
    "bottom": "alt, dip",
    "front": "ön",
    "form": "biçim, form; oluşturmak",
    "shape": "şekil; şekillendirmek",
    "size": "boyut, beden",
    "structure": "yapı",
    "pattern": "desen, kalıp, örüntü",
    "model": "model; örnek almak",
    "copy": "kopya; kopyalamak",
    "image": "görüntü, imaj",
    "picture": "resim, fotoğraf",
    "photo": "fotoğraf",
    "color": "renk",
    "sound": "ses; sağlam; gibi gelmek",
    "music": "müzik",
    "song": "şarkı",
    "art": "sanat",
    "book": "kitap; rezervasyon yapmak",
    "story": "hikaye, öykü; kat",
    "news": "haber(ler)",
    "newspaper": "gazete",
    "magazine": "dergi",
    "letter": "mektup; harf",
    "word": "kelime, sözcük; söz",
    "sentence": "cümle; ceza; mahkum etmek",
    "language": "dil, lisan",
    "speech": "konuşma, söylev",
    "name": "isim, ad; adlandırmak",
    "title": "başlık, unvan",
    "page": "sayfa",
    "paper": "kağıt; makale",
    "note": "not; fark etmek",
    "list": "liste; listelemek",
    "report": "rapor; bildirmek",
    "record": "kayıt; rekor; kaydetmek",
    "file": "dosya",
    "document": "belge",
    "card": "kart",
    "money": "para",
    "cash": "nakit",
    "price": "fiyat",
    "value": "değer; değer vermek",
    "worth": "değer, değerinde",
    "tax": "vergi",
    "budget": "bütçe",
    "income": "gelir",
    "profit": "kâr",
    "loss": "kayıp, zarar",
    "debt": "borç",
    "loan": "kredi, borç",
    "bank": "banka; kıyı",
    "banker": "bankacı",
    "account": "hesap; anlatım",
    "business": "iş, ticaret",
    "company": "şirket; eşlik",
    "companies": "şirketler",
    "industry": "sanayi, endüstri",
    "market": "pazar, piyasa",
    "customer": "müşteri",
    "client": "müvekkil, müşteri",
    "product": "ürün",
    "service": "hizmet, servis",
    "brand": "marka",
    "advertisement": "reklam",
    "job": "iş, meslek",
    "career": "kariyer",
    "profession": "meslek",
    "salary": "maaş",
    "wage": "ücret",
    "employee": "çalışan, işçi",
    "employer": "işveren",
    "manager": "müdür, yönetici",
    "boss": "patron, şef",
    "worker": "işçi, çalışan",
    "team": "takım, ekip",
    "group": "grup",
    "member": "üye",
    "leader": "lider, önder",
    "president": "başkan, cumhurbaşkanı",
    "government": "hükümet, devlet",
    "politician": "politikacı, siyasetçi",
    "politicians": "politikacılar",
    "policy": "politika, ilke",
    "politics": "siyaset, politika",
    "election": "seçim",
    "vote": "oy; oy vermek",
    "law": "yasa, hukuk",
    "legal": "yasal, hukuki",
    "illegal": "yasa dışı",
    "rule": "kural; yönetmek",
    "regulation": "düzenleme, yönetmelik",
    "regulations": "düzenlemeler, mevzuat",
    "right": "hak; doğru; sağ",
    "duty": "görev; gümrük vergisi",
    "responsibility": "sorumluluk",
    "freedom": "özgürlük",
    "justice": "adalet",
    "court": "mahkeme; kort",
    "judge": "yargıç; yargılamak",
    "police": "polis",
    "crime": "suç",
    "criminal": "suçlu; cezai",
    "prison": "hapishane",
    "war": "savaş",
    "peace": "barış, huzur",
    "army": "ordu",
    "soldier": "asker",
    "weapon": "silah",
    "gun": "silah, tabanca",
    "bomb": "bomba",
    "nuclear": "nükleer",
    "power": "güç, iktidar; elektrik",
    "energy": "enerji",
    "force": "kuvvet, güç; zorlamak",
    "strength": "güç, kuvvet",
    "pressure": "basınç, baskı",
    "heat": "ısı, sıcaklık; ısıtmak",
    "light": "ışık; hafif; yakmak",
    "dark": "karanlık, koyu",
    "sun": "güneş",
    "moon": "ay",
    "star": "yıldız",
    "sky": "gökyüzü",
    "weather": "hava durumu",
    "rain": "yağmur; yağmak",
    "snow": "kar",
    "wind": "rüzgar",
    "storm": "fırtına",
    "cloud": "bulut",
    "season": "mevsim; sezon",
    "spring": "ilkbahar; yay; kaynak",
    "summer": "yaz",
    "autumn": "sonbahar",
    "winter": "kış",
    "machine": "makine",
    "engine": "motor",
    "car": "araba",
    "bus": "otobüs",
    "train": "tren; eğitmek",
    "plane": "uçak; düzlem",
    "ship": "gemi; göndermek",
    "boat": "tekne, kayık",
    "bicycle": "bisiklet",
    "road": "yol",
    "street": "sokak, cadde",
    "bridge": "köprü",
    "station": "istasyon, durak",
    "airport": "havalimanı",
    "ticket": "bilet",
    "journey": "yolculuk",
    "trip": "gezi, seyahat",
    "tour": "tur, gezi",
    "map": "harita",
    "direction": "yön; talimat",
    "distance": "mesafe, uzaklık",
    "speed": "hız",
    "technology": "teknoloji",
    "computer": "bilgisayar",
    "internet": "internet",
    "website": "web sitesi",
    "software": "yazılım",
    "hardware": "donanım",
    "device": "cihaz, aygıt",
    "phone": "telefon",
    "screen": "ekran; perde",
    "button": "düğme, buton",
    "key": "anahtar; tuş; kilit önemde",
    "keyboard": "klavye",
    "network": "ağ, şebeke",
    "signal": "sinyal, işaret",
    "message": "mesaj, ileti",
    "email": "e-posta",
    "code": "kod; şifre",
    "program": "program",
    "application": "uygulama; başvuru",
    "user": "kullanıcı",
    "digital": "dijital, sayısal",
    "online": "çevrimiçi",
    "artificial": "yapay",
    "intelligence": "zeka; istihbarat",
    "algorithm": "algoritma",
    "algorithms": "algoritmalar",
    "robot": "robot",
    "machine": "makine",
    "tool": "araç, alet",
    "equipment": "ekipman, donanım",
    "material": "malzeme, madde; maddi",
    "metal": "metal",
    "gold": "altın",
    "silver": "gümüş",
    "iron": "demir; ütü",
    "glass": "cam; bardak",
    "wood": "ahşap, odun",
    "stone": "taş",
    "oil": "petrol; yağ",
    "gas": "gaz; benzin",
    "electricity": "elektrik",
    "fire": "ateş, yangın; kovmak",
    "smoke": "duman; sigara içmek",
    "idea": "fikir, düşünce",
    "opinion": "görüş, kanaat",
    "view": "görüş; manzara; bakmak",
    "belief": "inanç",
    "faith": "inanç, iman; güven",
    "religion": "din",
    "god": "tanrı",
    "soul": "ruh",
    "spirit": "ruh; moral",
    "culture": "kültür",
    "tradition": "gelenek",
    "custom": "adet, gelenek; özel yapım",
    "society": "toplum; dernek",
    "social": "sosyal, toplumsal",
    "community": "topluluk",
    "public": "halk; kamusal",
    "private": "özel, kişisel",
    "personal": "kişisel",
    "individual": "birey; bireysel",
    "population": "nüfus",
    "generation": "nesil, kuşak; üretim",
    "relationship": "ilişki",
    "marriage": "evlilik",
    "wedding": "düğün",
    "party": "parti; taraf",
    "event": "olay, etkinlik",
    "activity": "etkinlik, faaliyet",
    "experience": "deneyim, tecrübe; yaşamak",
    "opportunity": "fırsat",
    "chance": "şans, olasılık; fırsat",
    "risk": "risk; riske atmak",
    "danger": "tehlike",
    "safety": "güvenlik, emniyet",
    "security": "güvenlik",
    "trust": "güvenmek; güven",
    "hope": "umut; ummak",
    "fear": "korku; korkmak",
    "worry": "endişelenmek; endişe",
    "stress": "stres; vurgulamak",
    "anxiety": "kaygı, endişe",
    "happiness": "mutluluk",
    "joy": "sevinç, neşe",
    "pleasure": "zevk, keyif",
    "fun": "eğlence; eğlenceli",
    "surprise": "sürpriz; şaşırtmak",
    "anger": "öfke",
    "sadness": "üzüntü",
    "emotion": "duygu",
    "feeling": "his, duygu",
    "mood": "ruh hali",
    "attitude": "tutum, tavır",
    "behavior": "davranış",
    "habit": "alışkanlık",
    "character": "karakter; kişilik",
    "personality": "kişilik",
    "memory": "hafıza, bellek; anı",
    "dream": "rüya; hayal; hayal etmek",
    "attention": "dikkat, ilgi",
    "interest": "ilgi; faiz; çıkar",
    "curiosity": "merak",
    "skill": "beceri, yetenek",
    "ability": "yetenek, kabiliyet",
    "talent": "yetenek",
    "quality": "kalite, nitelik",
    "advantage": "avantaj, üstünlük",
    "disadvantage": "dezavantaj",
    "benefit": "fayda, yarar",
    "damage": "hasar, zarar; zarar vermek",
    "harm": "zarar; zarar vermek",
    "impact": "etki; çarpma",
    "influence": "etki; etkilemek",
    "difference": "fark",
    "similarity": "benzerlik",
    "comparison": "karşılaştırma",
    "choice": "seçim, tercih",
    "option": "seçenek",
    "possibility": "olasılık, ihtimal",
    "probability": "olasılık",
    "certainty": "kesinlik",
    "sport": "spor",
    "game": "oyun; maç; av",
    "match": "maç; kibrit; eşleşmek",
    "race": "yarış; ırk",
    "score": "skor, puan; gol atmak",
    "player": "oyuncu",
    "ball": "top; balo",
    "movie": "film",
    "film": "film; çekmek",
    "theater": "tiyatro",
    "stage": "sahne; aşama",
    "actor": "aktör, oyuncu",
    "audience": "izleyici, seyirci",
    "clothes": "giysiler, kıyafet",
    "dress": "elbise; giyinmek",
    "shirt": "gömlek",
    "shoe": "ayakkabı",
    "pocket": "cep",
    "bag": "çanta, torba",
    "box": "kutu",
    "bottle": "şişe",
    "cup": "fincan, kupa",
    "plate": "tabak; levha",
    "knife": "bıçak",
    "gift": "hediye; yetenek",
    "toy": "oyuncak",
    "clock": "saat (duvar)",
    "bell": "zil, çan",
    "mirror": "ayna",
    "camera": "kamera, fotoğraf makinesi",
    "radio": "radyo",
    "television": "televizyon",
    // ——— Sıfatlar ———
    "good": "iyi",
    "better": "daha iyi",
    "best": "en iyi",
    "bad": "kötü",
    "worse": "daha kötü",
    "worst": "en kötü",
    "great": "harika, büyük",
    "excellent": "mükemmel",
    "perfect": "kusursuz, mükemmel",
    "wonderful": "harika",
    "amazing": "şaşırtıcı, harika",
    "awesome": "müthiş, harika",
    "terrible": "korkunç, berbat",
    "horrible": "korkunç",
    "awful": "berbat, korkunç",
    "big": "büyük",
    "large": "büyük, geniş",
    "huge": "kocaman, devasa",
    "enormous": "muazzam, devasa, kocaman",
    "giant": "dev, devasa",
    "vast": "engin, uçsuz bucaksız",
    "massive": "devasa, kütlesel",
    "small": "küçük",
    "tiny": "minik, minicik",
    "short": "kısa",
    "long": "uzun",
    "tall": "uzun boylu",
    "high": "yüksek",
    "low": "alçak, düşük",
    "deep": "derin",
    "shallow": "sığ",
    "wide": "geniş",
    "narrow": "dar",
    "thick": "kalın; yoğun",
    "thin": "ince; zayıf",
    "heavy": "ağır",
    "strong": "güçlü, kuvvetli",
    "weak": "zayıf, güçsüz",
    "hard": "sert; zor",
    "soft": "yumuşak",
    "easy": "kolay",
    "difficult": "zor, güç",
    "simple": "basit, sade",
    "complex": "karmaşık",
    "complicated": "karmaşık",
    "hot": "sıcak; acı (biber)",
    "cold": "soğuk; nezle",
    "warm": "ılık, sıcak",
    "cool": "serin; havalı",
    "dry": "kuru; kurutmak",
    "wet": "ıslak",
    "clean": "temiz; temizlemek",
    "dirty": "kirli",
    "fresh": "taze",
    "new": "yeni",
    "old": "eski; yaşlı",
    "young": "genç",
    "modern": "modern, çağdaş",
    "ancient": "antik, eski",
    "early": "erken",
    "late": "geç; merhum",
    "recent": "son, yakın zamandaki",
    "current": "güncel, mevcut; akım",
    "beautiful": "güzel",
    "pretty": "güzel, hoş; oldukça",
    "handsome": "yakışıklı",
    "ugly": "çirkin",
    "nice": "hoş, güzel, iyi",
    "fine": "iyi, güzel; ince; ceza",
    "attractive": "çekici",
    "happy": "mutlu",
    "sad": "üzgün",
    "angry": "kızgın, öfkeli",
    "afraid": "korkmuş",
    "scared": "korkmuş",
    "nervous": "gergin, endişeli",
    "excited": "heyecanlı",
    "surprised": "şaşırmış",
    "bored": "sıkılmış",
    "boring": "sıkıcı",
    "interesting": "ilginç",
    "interested": "ilgili, ilgi duyan",
    "tired": "yorgun",
    "sick": "hasta",
    "healthy": "sağlıklı",
    "alive": "canlı, hayatta",
    "hungry": "aç",
    "thirsty": "susamış",
    "full": "dolu; tok",
    "rich": "zengin",
    "poor": "fakir, yoksul; zavallı",
    "expensive": "pahalı",
    "cheap": "ucuz",
    "free": "özgür; ücretsiz; boş",
    "busy": "meşgul, yoğun",
    "available": "mevcut, müsait",
    "ready": "hazır",
    "possible": "mümkün, olası",
    "impossible": "imkansız",
    "necessary": "gerekli",
    "important": "önemli",
    "essential": "temel, şart, zorunlu",
    "main": "ana, başlıca",
    "major": "büyük, önemli; binbaşı",
    "minor": "küçük, önemsiz; reşit olmayan",
    "significant": "önemli, kayda değer",
    "serious": "ciddi",
    "dangerous": "tehlikeli",
    "safe": "güvenli; kasa",
    "sure": "emin",
    "certain": "kesin, belirli",
    "clear": "açık, net; temizlemek",
    "obvious": "bariz, apaçık",
    "true": "doğru, gerçek",
    "false": "yanlış, sahte",
    "real": "gerçek",
    "wrong": "yanlış; haksız",
    "correct": "doğru; düzeltmek",
    "right": "doğru; sağ; hak",
    "exact": "tam, kesin",
    "accurate": "doğru, isabetli",
    "fair": "adil; fuar; sarışın",
    "unfair": "haksız, adaletsiz",
    "honest": "dürüst",
    "kind": "nazik; tür",
    "polite": "kibar",
    "rude": "kaba",
    "friendly": "arkadaş canlısı, dostça",
    "generous": "cömert",
    "selfish": "bencil",
    "brave": "cesur",
    "proud": "gururlu",
    "confident": "kendinden emin",
    "shy": "utangaç",
    "quiet": "sessiz, sakin",
    "loud": "gürültülü, yüksek sesli",
    "silent": "sessiz",
    "calm": "sakin",
    "crazy": "çılgın, deli",
    "smart": "zeki, akıllı",
    "clever": "zeki, akıllı",
    "intelligent": "zeki",
    "wise": "bilge, akıllı",
    "stupid": "aptal",
    "foolish": "aptalca, akılsız",
    "famous": "ünlü",
    "popular": "popüler, sevilen",
    "common": "yaygın, ortak",
    "rare": "nadir, az bulunur",
    "unique": "eşsiz, benzersiz",
    "special": "özel",
    "normal": "normal, olağan",
    "usual": "olağan, her zamanki",
    "strange": "garip, tuhaf",
    "weird": "tuhaf, acayip",
    "odd": "tuhaf; tek (sayı)",
    "typical": "tipik",
    "general": "genel; general",
    "specific": "belirli, özgül",
    "particular": "belirli, özel",
    "single": "tek; bekar",
    "double": "çift, iki kat",
    "extra": "ekstra, fazladan",
    "additional": "ek, ilave",
    "similar": "benzer",
    "equal": "eşit",
    "opposite": "zıt, karşı",
    "various": "çeşitli",
    "useful": "yararlı, kullanışlı",
    "useless": "yararsız, işe yaramaz",
    "helpful": "yardımcı, faydalı",
    "harmful": "zararlı",
    "effective": "etkili",
    "efficient": "verimli",
    "powerful": "güçlü",
    "powerless": "güçsüz, çaresiz",
    "successful": "başarılı",
    "wealthy": "varlıklı, zengin",
    "valuable": "değerli",
    "precious": "kıymetli, değerli",
    "empty": "boş",
    "complete": "tam, eksiksiz; tamamlamak",
    "entire": "tüm, bütün",
    "total": "toplam; tam",
    "final": "son, nihai; final",
    "last": "son; geçen; sürmek",
    "first": "ilk, birinci",
    "next": "sonraki, bir sonraki",
    "previous": "önceki",
    "former": "eski, önceki",
    "latter": "ikincisi, sonraki",
    "foreign": "yabancı",
    "international": "uluslararası",
    "national": "ulusal",
    "local": "yerel",
    "global": "küresel",
    "domestic": "yerli; evcil",
    "urban": "kentsel",
    "rural": "kırsal",
    "physical": "fiziksel",
    "mental": "zihinsel",
    "emotional": "duygusal",
    "spiritual": "ruhsal, manevi",
    "financial": "mali, finansal",
    "economic": "ekonomik",
    "economy": "ekonomi",
    "political": "siyasi, politik",
    "military": "askeri; ordu",
    "religious": "dini, dindar",
    "scientific": "bilimsel",
    "technical": "teknik",
    "professional": "profesyonel; meslek sahibi",
    "official": "resmi; yetkili",
    "formal": "resmi",
    "informal": "gayri resmi, samimi",
    "positive": "olumlu, pozitif",
    "negative": "olumsuz, negatif",
    "active": "aktif, etkin",
    "passive": "pasif, edilgen",
    "aware": "farkında",
    "conscious": "bilinçli, farkında",
    "unconscious": "bilinçsiz; baygın",
    "obviously": "açıkça, besbelli",
    "likely": "muhtemel, olası",
    "unlikely": "olasılık dışı",
    "willing": "istekli, gönüllü",
    "eager": "hevesli, istekli",
    "curious": "meraklı",
    "careful": "dikkatli",
    "careless": "dikkatsiz",
    "responsible": "sorumlu",
    "reliable": "güvenilir",
    "loyal": "sadık",
    "patient": "sabırlı; hasta",
    "gentle": "nazik, yumuşak",
    "cruel": "zalim, acımasız",
    "violent": "şiddetli, şiddet içeren",
    "peaceful": "huzurlu, barışçıl",
    "comfortable": "rahat, konforlu",
    "convenient": "uygun, elverişli",
    "suitable": "uygun",
    "appropriate": "uygun, yerinde",
    "proper": "uygun, doğru dürüst",
    "perfectly": "kusursuzca, tamamen",
    // ——— Kullanıcının metinlerindeki ve sık geçen ileri kelimeler ———
    "enormously": "son derece, muazzam ölçüde",
    "annihilation": "yok oluş, imha",
    "annihilate": "yok etmek, imha etmek",
    "evaporate": "buharlaşmak; yok olmak",
    "anthropomorphize": "insan özellikleri atfetmek, insanlaştırmak",
    "sentient": "duyarlı, hisseden, bilinçli",
    "creature": "yaratık, canlı",
    "creatures": "yaratıklar, canlılar",
    "peer": "akran, emsal; dikkatle bakmak",
    "peers": "akranlar, emsaller",
    "elite": "seçkin, elit",
    "shift": "kaymak, geçmek; vardiya; değişim",
    "shifted": "kaydı, geçti",
    "capture": "yakalamak, ele geçirmek",
    "accelerate": "hızlandırmak, hızlanmak",
    "strategy": "strateji",
    "phase": "aşama, evre",
    "advantage": "avantaj, üstünlük",
    "interview": "röportaj, mülakat; görüşmek",
    "interviewer": "görüşmeci, röportajı yapan",
    "manipulate": "manipüle etmek, yönlendirmek",
    "consciousness": "bilinç",
    "existence": "varoluş, varlık",
    "humanity": "insanlık",
    "civilization": "uygarlık, medeniyet",
    "revolution": "devrim",
    "evolution": "evrim",
    "innovation": "yenilik, inovasyon",
    "invention": "icat, buluş",
    "discovery": "keşif",
    "progress": "ilerleme; ilerlemek",
    "growth": "büyüme",
    "expansion": "genişleme",
    "transformation": "dönüşüm",
    "trend": "eğilim, akım",
    "pace": "tempo, hız",
    "scale": "ölçek; terazi; tırmanmak",
    "scope": "kapsam",
    "range": "aralık, menzil; çeşitlilik",
    "extent": "boyut, derece, kapsam",
    "limit": "sınır; sınırlamak",
    "boundary": "sınır",
    "threshold": "eşik",
    "barrier": "engel, bariyer",
    "obstacle": "engel",
    "challenge": "zorluk, meydan okuma",
    "threat": "tehdit",
    "crisis": "kriz, bunalım",
    "conflict": "çatışma, anlaşmazlık",
    "dispute": "anlaşmazlık; itiraz etmek",
    "debate": "tartışma, münazara",
    "negotiation": "müzakere, pazarlık",
    "agreement": "anlaşma, mutabakat",
    "contract": "sözleşme; kasılmak",
    "deal": "anlaşma; ilgilenmek",
    "commitment": "taahhüt, bağlılık",
    "obligation": "yükümlülük",
    "requirement": "gereklilik, şart",
    "standard": "standart, ölçüt",
    "criterion": "ölçüt, kriter",
    "principle": "ilke, prensip",
    "concept": "kavram",
    "notion": "kavram, fikir",
    "perspective": "bakış açısı, perspektif",
    "approach": "yaklaşım; yaklaşmak",
    "framework": "çerçeve",
    "context": "bağlam",
    "circumstance": "koşul, durum",
    "consequence": "sonuç, netice",
    "outcome": "sonuç",
    "implication": "sonuç, ima, anlam",
    "assumption": "varsayım",
    "hypothesis": "hipotez, varsayım",
    "evidence": "kanıt, delil",
    "proof": "kanıt, ispat",
    "argument": "argüman, sav; tartışma",
    "conclusion": "sonuç, vargı",
    "summary": "özet",
    "analysis": "analiz, çözümleme",
    "evaluation": "değerlendirme",
    "assessment": "değerlendirme",
    "estimate": "tahmin; tahmin etmek",
    "statistics": "istatistik",
    "survey": "anket; incelemek",
    "sample": "örnek, numune",
    "source": "kaynak",
    "resource": "kaynak",
    "fund": "fon; finanse etmek",
    "investment": "yatırım",
    "revenue": "gelir, hasılat",
    "expense": "gider, masraf",
    "wealth": "servet, zenginlik",
    "poverty": "yoksulluk",
    "inequality": "eşitsizlik",
    "employment": "istihdam",
    "unemployment": "işsizlik",
    "inflation": "enflasyon",
    "consumption": "tüketim",
    "production": "üretim",
    "distribution": "dağıtım, dağılım",
    "transportation": "ulaşım, taşımacılık",
    "infrastructure": "altyapı",
    "institution": "kurum",
    "organization": "kuruluş, örgüt",
    "corporation": "şirket, kurum",
    "foundation": "vakıf; temel",
    "authority": "otorite, yetki; yetkili makam",
    "administration": "yönetim, idare",
    "bureaucracy": "bürokrasi",
    "democracy": "demokrasi",
    "dictatorship": "diktatörlük",
    "citizen": "vatandaş, yurttaş",
    "immigrant": "göçmen",
    "refugee": "mülteci",
    "identity": "kimlik",
    "gender": "cinsiyet",
    "race": "ırk; yarış",
    "ethnic": "etnik",
    "minority": "azınlık",
    "majority": "çoğunluk",
    "diversity": "çeşitlilik",
    "discrimination": "ayrımcılık",
    "prejudice": "önyargı",
    "bias": "önyargı, yanlılık",
    "stereotype": "kalıp yargı, klişe",
    "reputation": "itibar, ün",
    "status": "statü, durum",
    "prestige": "prestij, saygınlık",
    "privilege": "ayrıcalık",
    "opportunity": "fırsat",
    "achievement": "başarı",
    "accomplishment": "başarı",
    "contribution": "katkı",
    "participation": "katılım",
    "cooperation": "işbirliği",
    "collaboration": "işbirliği",
    "competition": "rekabet, yarışma",
    "competitor": "rakip",
    "rival": "rakip",
    "opponent": "rakip, karşıt",
    "ally": "müttefik",
    "partner": "ortak, eş",
    "colleague": "meslektaş, iş arkadaşı",
    "expert": "uzman",
    "specialist": "uzman",
    "consultant": "danışman",
    "advisor": "danışman",
    "candidate": "aday",
    "applicant": "başvuran, aday",
    "volunteer": "gönüllü",
    "founder": "kurucu",
    "entrepreneur": "girişimci",
    "investor": "yatırımcı",
    "shareholder": "hissedar",
    "stakeholder": "paydaş",
    "consumer": "tüketici",
    "supplier": "tedarikçi",
    "manufacturer": "üretici, imalatçı",
    "retailer": "perakendeci",
    "vendor": "satıcı",
    "purchase": "satın almak; satın alma",
    "transaction": "işlem",
    "payment": "ödeme",
    "salary": "maaş",
    "bonus": "prim, ikramiye",
    "discount": "indirim",
    "bargain": "kelepir; pazarlık etmek",
    "auction": "açık artırma",
    "insurance": "sigorta",
    "mortgage": "ipotek, konut kredisi",
    "pension": "emekli maaşı",
    "savings": "birikim, tasarruf",
    "currency": "para birimi, döviz",
    "cryptocurrency": "kripto para",
    "cryptocurrencies": "kripto paralar",
    "bitcoin": "bitcoin",
    "blockchain": "blok zinciri",
    "database": "veritabanı",
    "server": "sunucu",
    "storage": "depolama",
    "cloud": "bulut",
    "download": "indirmek",
    "upload": "yüklemek",
    "update": "güncellemek; güncelleme",
    "upgrade": "yükseltmek; yükseltme",
    "install": "kurmak, yüklemek",
    "delete": "silmek",
    "search": "aramak; arama",
    "browse": "göz atmak, gezinmek",
    "click": "tıklamak; tık",
    "scroll": "kaydırmak",
    "swipe": "kaydırmak (parmakla)",
    "type": "yazmak; tür",
    "text": "metin; mesaj atmak",
    "content": "içerik; memnun",
    "media": "medya",
    "platform": "platform",
    "channel": "kanal",
    "stream": "akış; yayın; dere",
    "broadcast": "yayın; yayınlamak",
    "publish": "yayımlamak",
    "advertise": "reklam yapmak",
    "promote": "tanıtmak; terfi ettirmek",
    "recommend": "önermek, tavsiye etmek",
    "review": "incelemek; inceleme, yorum",
    "rating": "derecelendirme, puan",
    "feedback": "geri bildirim",
    "comment": "yorum; yorum yapmak",
    "response": "yanıt, tepki",
    "reaction": "tepki, reaksiyon",
    "interaction": "etkileşim",
    "communication": "iletişim",
    "conversation": "sohbet, konuşma",
    "discussion": "tartışma, görüşme",
    "dialogue": "diyalog",
    "statement": "ifade, açıklama",
    "announcement": "duyuru",
    "declaration": "bildiri, ilan",
    "explanation": "açıklama",
    "description": "tanım, açıklama",
    "definition": "tanım",
    "instruction": "talimat, yönerge",
    "guideline": "kılavuz ilke, yönerge",
    "manual": "kılavuz; elle yapılan",
    "procedure": "prosedür, işlem",
    "operation": "işlem, operasyon; ameliyat",
    "function": "işlev; çalışmak",
    "feature": "özellik",
    "characteristic": "özellik, karakteristik",
    "property": "mülk; özellik",
    "attribute": "nitelik; atfetmek",
    "element": "öğe, unsur; element",
    "component": "bileşen, parça",
    "detail": "ayrıntı, detay",
    "aspect": "yön, boyut",
    "factor": "etken, faktör",
    "variable": "değişken",
    "category": "kategori, ulam",
    "classification": "sınıflandırma",
    "hierarchy": "hiyerarşi",
    "priority": "öncelik",
    "emphasis": "vurgu",
    "focus": "odak; odaklanmak",
    "concentration": "konsantrasyon, yoğunlaşma",
    "dedication": "adanmışlık, özveri",
    "discipline": "disiplin",
    "motivation": "motivasyon, güdü",
    "inspiration": "ilham",
    "ambition": "hırs, tutku",
    "passion": "tutku",
    "enthusiasm": "coşku, şevk",
    "determination": "kararlılık, azim",
    "persistence": "sebat, ısrar",
    "patience": "sabır",
    "courage": "cesaret",
    "confidence": "güven, özgüven",
    "pride": "gurur",
    "dignity": "onur, haysiyet",
    "honor": "onur, şeref; onurlandırmak",
    "respect": "saygı; saygı duymak",
    "admiration": "hayranlık",
    "gratitude": "minnettarlık, şükran",
    "sympathy": "sempati; başsağlığı",
    "empathy": "empati",
    "compassion": "merhamet, şefkat",
    "mercy": "merhamet",
    "forgiveness": "affetme, bağışlama",
    "apology": "özür",
    "regret": "pişmanlık; pişman olmak",
    "guilt": "suçluluk",
    "shame": "utanç; ayıp",
    "embarrassment": "mahcubiyet, utanma",
    "frustration": "hayal kırıklığı, bezginlik",
    "disappointment": "hayal kırıklığı",
    "grief": "keder, yas",
    "sorrow": "üzüntü, keder",
    "despair": "umutsuzluk, çaresizlik",
    "loneliness": "yalnızlık",
    "isolation": "yalıtım, tecrit; yalnızlık",
    "solitude": "yalnızlık, inziva",
    "silence": "sessizlik",
    "noise": "gürültü",
    "chaos": "kaos, karmaşa",
    "confusion": "kafa karışıklığı",
    "clarity": "netlik, açıklık",
    "precision": "kesinlik, hassasiyet",
    "accuracy": "doğruluk, isabet",
    "error": "hata",
    "mistake": "hata, yanlış",
    "fault": "kusur, hata; fay",
    "flaw": "kusur",
    "defect": "kusur, defo",
    "weakness": "zayıflık",
    "vulnerability": "savunmasızlık, zafiyet",
    "resilience": "dayanıklılık, direnç",
    "endurance": "dayanıklılık, tahammül",
    "survival": "hayatta kalma",
    "extinction": "yok oluş, nesil tükenmesi",
    "destruction": "yıkım, tahribat",
    "collapse": "çöküş; çökmek",
    "disaster": "felaket, afet",
    "catastrophe": "felaket, yıkım",
    "emergency": "acil durum",
    "rescue": "kurtarmak; kurtarma",
    "recovery": "iyileşme, toparlanma",
    "restoration": "restorasyon, onarım",
    "maintenance": "bakım",
    "repair": "onarmak; onarım",
    "replacement": "değiştirme, yedek",
    "substitute": "yedek; yerine geçmek",
    "alternative": "alternatif, seçenek",
    "equivalent": "eşdeğer",
    "version": "sürüm, versiyon",
    "edition": "baskı, sürüm",
    "original": "orijinal, özgün; asıl",
    "authentic": "otantik, gerçek",
    "genuine": "hakiki, samimi",
    "fake": "sahte",
    "artificial": "yapay",
    "virtual": "sanal",
    "reality": "gerçeklik",
    "illusion": "yanılsama, illüzyon",
    "fantasy": "fantezi, hayal",
    "imagination": "hayal gücü",
    "creativity": "yaratıcılık",
    "originality": "özgünlük",
    "masterpiece": "başyapıt, şaheser",
    "literature": "edebiyat",
    "poetry": "şiir",
    "novel": "roman; yeni, özgün",
    "author": "yazar",
    "writer": "yazar",
    "reader": "okuyucu",
    "publisher": "yayıncı",
    "chapter": "bölüm",
    "paragraph": "paragraf",
    "phrase": "ifade, kalıp",
    "vocabulary": "kelime hazinesi, sözcük dağarcığı",
    "grammar": "dil bilgisi, gramer",
    "pronunciation": "telaffuz",
    "accent": "aksan; vurgu",
    "dialect": "lehçe, ağız",
    "translation": "çeviri, tercüme",
    "translate": "çevirmek, tercüme etmek",
    "interpret": "yorumlamak; sözlü çevirmek",
    "interpretation": "yorum; sözlü çeviri",
    "meaning": "anlam",
    "mean": "anlamına gelmek, demek istemek; ortalama; cimri",
    "meant": "kastetti; anlamına geldi",
    "significance": "önem, anlam",
    "relevance": "ilgililik, alaka",
    "importance": "önem",
    "urgency": "aciliyet",
    "necessity": "gereklilik, zorunluluk",
    "luxury": "lüks",
    "comfort": "rahatlık, konfor; teselli etmek",
    "convenience": "kolaylık, rahatlık",
    "efficiency": "verimlilik",
    "productivity": "üretkenlik, verimlilik",
    "performance": "performans; gösteri",
    "capacity": "kapasite",
    "capability": "yetenek, kapasite",
    "potential": "potansiyel; olası",
    "possibility": "olasılık",
    "prospect": "beklenti, olasılık",
    "expectation": "beklenti",
    "anticipation": "beklenti, öngörü",
    "preparation": "hazırlık",
    "arrangement": "düzenleme",
    "schedule": "program, çizelge; planlamak",
    "appointment": "randevu; atama",
    "deadline": "son tarih, teslim tarihi",
    "duration": "süre",
    "interval": "aralık",
    "frequency": "sıklık, frekans",
    "occasion": "vesile, fırsat; özel gün",
    "ceremony": "tören",
    "celebration": "kutlama",
    "festival": "festival, şenlik",
    "anniversary": "yıl dönümü",
    "holiday": "tatil; bayram",
    "vacation": "tatil",
    "leisure": "boş zaman",
    "entertainment": "eğlence",
    "amusement": "eğlence",
    "recreation": "dinlence, eğlence",
    "hobby": "hobi, uğraş",
    "exercise": "egzersiz; alıştırma",
    "training": "eğitim, antrenman",
    "coach": "antrenör; koçluk etmek",
    "athlete": "sporcu, atlet",
    "champion": "şampiyon",
    "tournament": "turnuva",
    "victory": "zafer",
    "defeat": "yenilgi; yenmek",
    "triumph": "zafer, büyük başarı",
    "struggle": "mücadele; mücadele etmek",
    "battle": "muharebe, savaş",
    "campaign": "kampanya; sefer",
    "mission": "görev, misyon",
    "task": "görev, iş",
    "assignment": "ödev, görev",
    "project": "proje",
    "initiative": "girişim, inisiyatif",
    "venture": "girişim; cesaret etmek",
    "enterprise": "girişim, teşebbüs",
    "startup": "girişim, yeni şirket",
    "budget": "bütçe",
    "estimate": "tahmin",
    "proposal": "öneri, teklif",
    "presentation": "sunum",
    "conference": "konferans",
    "seminar": "seminer",
    "workshop": "atölye, çalıştay",
    "session": "oturum, seans",
    "committee": "komite, kurul",
    "board": "kurul; tahta; binmek",
    "council": "konsey, meclis",
    "parliament": "parlamento, meclis",
    "congress": "kongre",
    "senate": "senato",
    "ministry": "bakanlık",
    "department": "bölüm, departman",
    "division": "bölüm; bölme",
    "branch": "şube; dal",
    "headquarters": "genel merkez, karargah",
    "facility": "tesis; kolaylık",
    "laboratory": "laboratuvar",
    "factory": "fabrika",
    "warehouse": "depo, ambar",
    "shop": "dükkan; alışveriş yapmak",
    "store": "mağaza; depolamak",
    "mall": "alışveriş merkezi",
    "supermarket": "süpermarket",
    "pharmacy": "eczane",
    "bakery": "fırın, pastane",
    "library": "kütüphane",
    "museum": "müze",
    "gallery": "galeri",
    "church": "kilise",
    "mosque": "cami",
    "temple": "tapınak",
    "palace": "saray",
    "castle": "kale, şato",
    "tower": "kule",
    "monument": "anıt",
    "statue": "heykel",
    "square": "meydan; kare",
    "park": "park; park etmek",
    "playground": "oyun alanı",
    "stadium": "stadyum",
    "gym": "spor salonu",
    "pool": "havuz; ortak fon",
    "beach": "plaj, kumsal",
    "island": "ada",
    "coast": "kıyı, sahil",
    "harbor": "liman",
    "port": "liman; bağlantı noktası",
    "border": "sınır",
    "frontier": "sınır; öncü alan",
    "territory": "bölge, toprak",
    "continent": "kıta",
    "hemisphere": "yarım küre",
    "equator": "ekvator",
    "climate": "iklim",
    "temperature": "sıcaklık",
    "humidity": "nem",
    "drought": "kuraklık",
    "flood": "sel; su basmak",
    "earthquake": "deprem",
    "volcano": "yanardağ",
    "hurricane": "kasırga",
    "tornado": "hortum, kasırga",
    "lightning": "şimşek, yıldırım",
    "thunder": "gök gürültüsü",
    "rainbow": "gökkuşağı",
    "sunrise": "gün doğumu",
    "sunset": "gün batımı",
    "shadow": "gölge",
    "reflection": "yansıma; düşünme",
    "atmosphere": "atmosfer; ortam",
    "oxygen": "oksijen",
    "carbon": "karbon",
    "pollution": "kirlilik",
    "waste": "atık; israf etmek",
    "recycling": "geri dönüşüm",
    "sustainability": "sürdürülebilirlik",
    "conservation": "koruma",
    "wildlife": "yaban hayatı",
    "species": "tür (canlı)",
    "organism": "organizma, canlı",
    "bacteria": "bakteri",
    "virus": "virüs",
    "vaccine": "aşı",
    "infection": "enfeksiyon",
    "epidemic": "salgın",
    "pandemic": "pandemi, küresel salgın",
    "symptom": "belirti, semptom",
    "diagnosis": "teşhis, tanı",
    "therapy": "terapi, tedavi",
    "surgery": "ameliyat, cerrahi",
    "prescription": "reçete",
    "pharmacy": "eczane",
    "nutrition": "beslenme",
    "diet": "diyet, beslenme düzeni",
    "protein": "protein",
    "vitamin": "vitamin",
    "calorie": "kalori",
    "obesity": "obezite",
    "fitness": "form, zindelik",
    "wellness": "sağlıklı yaşam, esenlik",
    "hygiene": "hijyen, temizlik",
    "sanitation": "sanitasyon, hıfzıssıhha",
    // ——— Yapay zekâ / teknoloji söylemi ———
    "doomer": "felaketçi, kıyamet senaryocusu",
    "doomers": "felaketçiler, kıyamet senaryocuları",
    "doom": "felaket, kıyamet; mahkum etmek",
    "dystopia": "distopya, karanlık gelecek",
    "dystopian": "distopik",
    "utopia": "ütopya",
    "utopian": "ütopik, hayalci",
    "singularity": "tekillik",
    "sentience": "duyarlılık, hissetme yetisi",
    "superintelligence": "süper zekâ",
    "alignment": "hizalama, uyum",
    "chatbot": "sohbet robotu",
    "prompt": "komut, yönlendirme; harekete geçirmek",
    "automation": "otomasyon",
    "automate": "otomatikleştirmek",
    "autonomous": "özerk, otonom",
    "drone": "insansız hava aracı, dron",
    "cyborg": "sayborg",
    "simulation": "simülasyon, benzetim",
    "simulate": "simüle etmek, taklit etmek",
    "neural": "sinirsel, nöral",
    "quantum": "kuantum",
    "genome": "genom",
    "gene": "gen",
    "clone": "klon; klonlamak",
    "mutation": "mutasyon, değişinim",
    "biotech": "biyoteknoloji",
    "nanotech": "nanoteknoloji",
    "surveillance": "gözetim, izleme",
    "privacy": "mahremiyet, gizlilik",
    "encryption": "şifreleme",
    "hacker": "bilgisayar korsanı, hacker",
    "cybersecurity": "siber güvenlik",
    "misinformation": "yanlış bilgi",
    "disinformation": "dezenformasyon, kasıtlı yanlış bilgi",
    "propaganda": "propaganda",
    "censorship": "sansür",
    "manipulation": "manipülasyon, güdümleme",
    "polarization": "kutuplaşma",
    "radicalization": "radikalleşme",
    "extremism": "aşırıcılık, ekstremizm",
    "conspiracy": "komplo",
    "skeptic": "şüpheci, septik",
    "skeptical": "şüpheci, kuşkulu",
    "optimist": "iyimser",
    "optimistic": "iyimser",
    "pessimist": "kötümser",
    "pessimistic": "kötümser, karamsar",
    "existential": "varoluşsal",
    "apocalypse": "kıyamet",
    "apocalyptic": "kıyamet gibi, kıyametvari"
};
